config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/testerpyo:
      branch: main
      repo: https://github.com/GuillermoDiazSM/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-flax-otter.sh
        container: qc.acc_sleazy-rust-alligator
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-burgundy-lemming.sh
        container: qc.doc_jumpy-maroon-cockroach
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-grey-wolverine.sh
        container: qc.doc_surly-brass-dunker
      github.com/GuillermoDiazSM/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-persimmon-earwig.sh
        container: qc.doc_paltry-smalt-giraffe
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-mauve-russel.sh
        container: qc.lic_geeky-green-crane
  QC.Sec:
    repos:
      github.com/GuillermoDiazSM/testerpyo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-cardinal-dalmatian.sh
        container: qc.sec_goopy-khaki-nightingale
  QC.Sty:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-puce-markhor.sh
        container: qc.sty_slimy-smalt-wasp
  QC.Uni:
    repos:
      github.com/GuillermoDiazSM/testerpyo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-jade-coral.sh
        container: qc.uni_sloppy-lime-squirrel
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-flax-wildebeest.sh
        container: qc.ver_gummy-purple-cougar
timeout: 5400
