config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/testerpyo:
      branch: main
      repo: https://github.com/GuillermoDiazSM/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-burgundy-starfish.sh
        container: qc.acc_cloudy-goldenrod-olm
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-beige-elephant.sh
        container: qc.doc_wheezy-saffron-macaque
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cinnamon-nightingale.sh
        container: qc.doc_paltry-beige-burmese
      github.com/GuillermoDiazSM/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cream-lynx.sh
        container: qc.doc_scummy-magenta-greyhound
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-grey-coral.sh
        container: qc.lic_freaky-amber-nightingale
  QC.Sec:
    repos:
      github.com/GuillermoDiazSM/testerpyo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-yellow-javanese.sh
        container: qc.sec_grumpy-olivine-labradoodle
  QC.Sty:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-smalt-gharial.sh
        container: qc.sty_randy-champagne-tortoise
  QC.Uni:
    repos:
      github.com/GuillermoDiazSM/testerpyo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-emerald-spider.sh
        container: qc.uni_tasty-grey-rabbit
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-turquoise-buffalo.sh
        container: qc.ver_stinky-seashell-russel
timeout: 5400
