config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/testerpyo:
      branch: main
      repo: https://github.com/GuillermoDiazSM/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-blue-dane.sh
        container: qc.acc_goopy-cinnabar-worm
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-malachite-akbash.sh
        container: qc.doc_skimpy-charcoal-iguana
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-ivory-molly.sh
        container: qc.doc_messy-tangerine-gorilla
      github.com/GuillermoDiazSM/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-maroon-cow.sh
        container: qc.doc_pasty-ruby-cattle
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-crimson-lizard.sh
        container: qc.lic_lovely-coral-impala
  QC.Sec:
    repos:
      github.com/GuillermoDiazSM/testerpyo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lavender-bird.sh
        container: qc.sec_craggy-gamboge-abyssinian
  QC.Sty:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-persimmon-slug.sh
        container: qc.sty_chummy-asparagus-dragon
  QC.Uni:
    repos:
      github.com/GuillermoDiazSM/testerpyo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-aqua-mastiff.sh
        container: qc.uni_whiny-ivory-paradise
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-lavender-goat.sh
        container: qc.ver_shaggy-persimmon-bloodhound
timeout: 5400
