config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/testerpyo:
      branch: main
      repo: https://github.com/GuillermoDiazSM/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-chocolate-manatee.sh
        container: qc.acc_gummy-linen-burmese
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-peach-kudu.sh
        container: qc.doc_crabby-bronze-lion
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-salmon-jaguar.sh
        container: qc.doc_droopy-asparagus-chihuahua
      github.com/GuillermoDiazSM/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ivory-neanderthal.sh
        container: qc.doc_hasty-ruby-vole
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-pink-panda.sh
        container: qc.lic_flaky-ecru-quokka
  QC.Sec:
    repos:
      github.com/GuillermoDiazSM/testerpyo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-red-bird.sh
        container: qc.sec_frumpy-russet-forest
  QC.Sty:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-olive-moorhen.sh
        container: qc.sty_fuzzy-platinum-giraffe
  QC.Uni:
    repos:
      github.com/GuillermoDiazSM/testerpyo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lemon-spitz.sh
        container: qc.uni_woozy-mustard-deer
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-firebrick-bullfrog.sh
        container: qc.ver_slimy-turquoise-mist
timeout: 5400
