config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/testerpyo:
      branch: main
      repo: https://github.com/GuillermoDiazSM/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-coral-snake.sh
        container: qc.acc_craggy-cinnamon-mastiff
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-red-caterpillar.sh
        container: qc.doc_sickly-pumpkin-liger
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-black-avocet.sh
        container: qc.doc_crappy-goldenrod-albatross
      github.com/GuillermoDiazSM/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-bistre-squirt.sh
        container: qc.doc_flimsy-cornflower-echidna
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-malachite-squid.sh
        container: qc.lic_stealthy-ecru-hyena
  QC.Sec:
    repos:
      github.com/GuillermoDiazSM/testerpyo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-salmon-lionfish.sh
        container: qc.sec_boozy-periwinkle-devil
  QC.Sty:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-turquoise-wallaby.sh
        container: qc.sty_lousy-smalt-mist
  QC.Uni:
    repos:
      github.com/GuillermoDiazSM/testerpyo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-taupe-coral.sh
        container: qc.uni_snazzy-gold-shrew
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-chartreuse-labradoodle.sh
        container: qc.ver_freaky-zucchini-kudu
timeout: 5400
