config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/testerpyo:
      branch: main
      repo: https://github.com/GuillermoDiazSM/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-zucchini-grouse.sh
        container: qc.acc_skimpy-corn-dane
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-magenta-bee.sh
        container: qc.doc_sleepy-coral-macaw
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cinnamon-labradoodle.sh
        container: qc.doc_wheezy-seashell-affenpinscher
      github.com/GuillermoDiazSM/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-wheat-dugong.sh
        container: qc.doc_geeky-bronze-shrimp
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-silver-dhole.sh
        container: qc.lic_whiny-harlequin-chihuahua
  QC.Sec:
    repos:
      github.com/GuillermoDiazSM/testerpyo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-tangerine-bongo.sh
        container: qc.sec_muzzy-harlequin-eel
  QC.Sty:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-silver-salamander.sh
        container: qc.sty_woozy-maroon-zorse
  QC.Uni:
    repos:
      github.com/GuillermoDiazSM/testerpyo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-lavender-wallaby.sh
        container: qc.uni_dorky-peach-chamois
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-aqua-wasp.sh
        container: qc.ver_sleazy-celadon-impala
timeout: 5400
