config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/testerpyo:
      branch: main
      repo: https://github.com/GuillermoDiazSM/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-malachite-monster.sh
        container: qc.acc_beady-wisteria-bonobo
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-amaranth-rabbit.sh
        container: qc.doc_fuzzy-tomato-beaver
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cinnabar-flamingo.sh
        container: qc.doc_scummy-bistre-mammoth
      github.com/GuillermoDiazSM/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-charcoal-eagle.sh
        container: qc.doc_craggy-brown-dragon
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cornflower-hound.sh
        container: qc.lic_snazzy-grey-okapi
  QC.Sec:
    repos:
      github.com/GuillermoDiazSM/testerpyo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-tomato-bulldog.sh
        container: qc.sec_geeky-tomato-chinook
  QC.Sty:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-salmon-chipmunk.sh
        container: qc.sty_lumpy-amethyst-blue
  QC.Uni:
    repos:
      github.com/GuillermoDiazSM/testerpyo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-chocolate-liger.sh
        container: qc.uni_scummy-amber-bat
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-indigo-tiger.sh
        container: qc.ver_snappy-green-fowl
timeout: 5400
