config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/testerpyo:
      branch: main
      repo: https://github.com/GuillermoDiazSM/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-gamboge-cassowary.sh
        container: qc.acc_whiny-heliotrope-goat
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-mauve-numbat.sh
        container: qc.doc_cheeky-russet-hornet
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-celadon-macaw.sh
        container: qc.doc_woozy-apricot-fowl
      github.com/GuillermoDiazSM/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-orange-heron.sh
        container: qc.doc_whiny-pear-squirrel
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-tan-emu.sh
        container: qc.lic_queasy-aquamarine-pinscher
  QC.Sec:
    repos:
      github.com/GuillermoDiazSM/testerpyo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-saffron-impala.sh
        container: qc.sec_hasty-copper-blue
  QC.Sty:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-maroon-caracal.sh
        container: qc.sty_zippy-khaki-rottweiler
  QC.Uni:
    repos:
      github.com/GuillermoDiazSM/testerpyo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-black-bongo.sh
        container: qc.uni_droopy-russet-heron
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-gamboge-toad.sh
        container: qc.ver_clammy-asparagus-lynx
timeout: 5400
