config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/testerpyo:
      branch: main
      repo: https://github.com/GuillermoDiazSM/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-harlequin-moose.sh
        container: qc.acc_trippy-champagne-snake
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-magnolia-badger.sh
        container: qc.doc_surly-azure-swan
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-mauve-seahorse.sh
        container: qc.doc_gummy-amethyst-zebra
      github.com/GuillermoDiazSM/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-charcoal-bison.sh
        container: qc.doc_snappy-champagne-olm
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-thistle-eagle.sh
        container: qc.lic_freaky-firebrick-dodo
  QC.Sec:
    repos:
      github.com/GuillermoDiazSM/testerpyo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-grey-bat.sh
        container: qc.sec_stealthy-magnolia-mammoth
  QC.Sty:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-carmine-spoonbill.sh
        container: qc.sty_thirsty-thistle-snail
  QC.Uni:
    repos:
      github.com/GuillermoDiazSM/testerpyo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-olivine-spoonbill.sh
        container: qc.uni_gummy-mustard-loon
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-magenta-seal.sh
        container: qc.ver_snazzy-celadon-squirt
timeout: 5400
