config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/testerpyo:
      branch: main
      repo: https://github.com/GuillermoDiazSM/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-khaki-devil.sh
        container: qc.acc_queasy-wisteria-dunker
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-lime-dachshund.sh
        container: qc.doc_geeky-magnolia-snake
      github.com/GuillermoDiazSM/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-lemon-capybara.sh
        container: qc.doc_craggy-blue-bracke
      github.com/GuillermoDiazSM/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-bronze-butterfly.sh
        container: qc.doc_sunny-orchid-stoat
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-buff-baboon.sh
        container: qc.lic_craggy-plum-chinook
  QC.Sec:
    repos:
      github.com/GuillermoDiazSM/testerpyo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-orange-tzu.sh
        container: qc.sec_beady-saffron-chinchilla
  QC.Sty:
    repos:
      github.com/GuillermoDiazSM/testerpyo find_oph_workflows.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cardinal-spitz.sh
        container: qc.sty_shaggy-firebrick-chihuahua
  QC.Uni:
    repos:
      github.com/GuillermoDiazSM/testerpyo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-rust-scorpion.sh
        container: qc.uni_snazzy-seashell-quokka
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-jade-uakari.sh
        container: qc.ver_seedy-aquamarine-whippet
timeout: 5400
